### ISSUE TITLE
This code doesnt let me use the bot

### ISSUE THREAD

**Issue by ConquestorDev** [greys-bots/ticket-golem#3]
files = fs.readdirSync(__dirname + '/migrations');
	var version = (await db.query(`SELECT * FROM extras WHERE key = 'version'`)).rows[0]?.
val || -1;

**Comment by selenated** [comment]
Can you explain the problem exactly? If there's an error, what does it say?

**Comment by selenated** [comment]
Hi, I still need more information on this in order to help. If you can't provide that information I'll have to close this issue for now

**Comment by selenated** [comment]
Closing due to lack of response
